import { abrir } from './arnes.mjs';
const s=await abrir({out:'/tmp/macondo-expansion'});
await s.entrar();
await s.js(`document.querySelector('#onboarding button').click()`);
s.afirmar(await s.js(`!!__macondo.experience.scene.getObjectByName('rio-corriente')`),'río renderizado');
await s.js(`__macondo.player.place(0,24,0)`);
await s.esperar(`document.querySelector('#open-discoveries').textContent.includes('1/6')`);
s.afirmar(await s.js(`JSON.parse(localStorage.getItem('macondo-hallazgos-v1')).includes('umbral')`),'hallazgo persistido');
await s.clic('#open-discoveries');
s.afirmar(await s.js(`document.querySelector('#discoveries').open && document.querySelectorAll('#discovery-list li').length===6`),'álbum con seis entradas');
await s.captura('album');
await s.js(`document.querySelector('#discoveries').close()`);
await s.js(`__macondo.player.place(-29.5,8,1.57)`);
await s.esperar(`document.querySelector('#open-discoveries').textContent.includes('2/6')`);
await s.captura('rio');
const before=await s.js(`__macondo.experience.scene.getObjectByName('rio-corriente').material.uniforms.time.value`);
await s.clic('#motion');
const paused=await s.js(`__macondo.experience.scene.getObjectByName('rio-corriente').material.uniforms.time.value`);
await s.captura('rio-pausa');
s.afirmar(await s.js(`__macondo.experience.scene.getObjectByName('rio-corriente').material.uniforms.time.value === ${paused}`),'pausa congela agua');
s.afirmar(paused>=before,'reloj del agua coherente');
await s.clic('#help-btn');
await s.js(`const q=document.querySelector('#quality-mode'); q.value='light'; q.dispatchEvent(new Event('change'));`);
s.afirmar(await s.js(`!__macondo.experience.renderer.shadowMap.enabled && __macondo.experience.renderer.getPixelRatio()<=1`),'modo ligero reduce sombras y resolución');
await s.js(`document.querySelector('#help').close()`);
await s.movil();
s.afirmar(await s.puedeClic('#open-discoveries'),'álbum accesible en móvil');
s.afirmar(await s.js(`document.documentElement.scrollWidth<=innerWidth`),'sin desborde móvil');
await s.captura('movil');
await s.escritorio();
await s.js(`__macondo.player.place(0,3.5,0)`);
await s.clic('#motion');
await s.captura('fuente');
await s.cerrar();
